// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"myiot/user/rpc/internal/logic"
	"myiot/user/rpc/internal/svc"
	"myiot/user/rpc/types/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Auth(ctx context.Context, in *pb.UserAuthRequest) (*pb.UserAuthReply, error) {
	l := logic.NewAuthLogic(ctx, s.svcCtx)
	return l.Auth(in)
}
